# Homebrew formula for bmad
# This formula is auto-generated by GoReleaser during releases
# For manual installation: brew tap robertguss/bmad && brew install bmad

class Bmad < Formula
  desc "TUI application for automating story development with Claude CLI"
  homepage "https://github.com/robertguss/bmad-automate-go"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/robertguss/bmad-automate-go/releases/download/v#{version}/bmad_Darwin_x86_64.tar.gz"
      # sha256 will be filled in by goreleaser
    end

    on_arm do
      url "https://github.com/robertguss/bmad-automate-go/releases/download/v#{version}/bmad_Darwin_arm64.tar.gz"
      # sha256 will be filled in by goreleaser
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robertguss/bmad-automate-go/releases/download/v#{version}/bmad_Linux_x86_64.tar.gz"
      # sha256 will be filled in by goreleaser
    end

    on_arm do
      url "https://github.com/robertguss/bmad-automate-go/releases/download/v#{version}/bmad_Linux_arm64.tar.gz"
      # sha256 will be filled in by goreleaser
    end
  end

  depends_on "git" => :optional

  def install
    bin.install "bmad"
  end

  test do
    system "#{bin}/bmad", "--version"
  end
end
